#基础配置

spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
#
#  application:
#    name: xuegao-nacos-config-client
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 #Nacos服务注册中心地址
#      config:
##        server-addr file-extension 在8848上找一个yaml文件，环境是Dev模式的
#        server-addr: localhost:8848 #Nacos作为配置中心地址
#        file-extension: yaml #指定yaml格式的配置
#        group: DEV_GROUP
#        namespace: 7d8f0f5a-6a53-4785-9686-dd460158e5d4

# nacos配置
#server:
#  port: 3377






# nacos-config-client-dev.yaml
# nacos-config-client-test.yaml   ----> config.info