server:
  port: 8401
spring:
  application:
    name: xuegao-nacos-sentinel8401
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
#        配置 sentinel dashboard 的地址
        dashboard: localhost:8080
#        默认8719端口，假如被占用会自动从8719开始一次+1扫描，直至找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      #      监控的端点 全部打开
      exposure:
        include: '*'
    jmx:
      exposure:
        exclude: '*'