server:
  port: 14000
spring:
  application:
    name: xuegao-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:

#消费者将要去访问的微服务名称 注册成功进入nacos的微服务提供者
#  nacos-payment-provider 服务名 application。name
service-url:
  nacos-user-service: http://xuegao-nacos-provider
